### ISSUE TITLE
Unable to log out

### ISSUE THREAD

**Issue by NathanGloyn** [dddsw/dddsouthwest-web#2]
After registering on the site I attempted to log out, it appeared to work but then on returning to the site I am still logged in.

Steps to reproduce:

- register on the site
- click log out
- when presented with screen asking if want to log out of identity server click log out
- screen will now tell you you are logged out
- go back to the main site and you will still be logged in

If you attempt the above and click log out again you have slightly different behaviour in that you will just see the screen telling you that you are logged out

**Comment by josephwoodward** [comment]
Thanks for raising this, I'm hoping to get this sorted in the next day or so.

**Comment by slang25** [comment]
![no way out](https://vignette.wikia.nocookie.net/samandcat/images/9/9c/There_is_no_way_out.gif/revision/latest?cb=20120802231910)

**Comment by josephwoodward** [comment]
Fixed in the latest release, thanks for reporting @NathanGloyn :)
