### ISSUE TITLE
Site returns HTTP 500 for email address that isn't recognised

### ISSUE THREAD

**Issue by robinminto** [dddsw/dddsouthwest-web#3]
If I enter an email address that isn't recognised, HTTP 500 is returned to the browser (rather than allowing me to try again)

1. Click on LOGIN from the homepage
2. Enter an email address that isn't already registered
3. Enter any password
4. Click the Login button

**Comment by josephwoodward** [comment]
Thanks for these, hoping to tackle this one tonight.

**Comment by josephwoodward** [comment]
This has also been fixed in the latest release :)
