### ISSUE TITLE
Logout page text blends into background

### ISSUE THREAD

**Issue by robinminto** [dddsw/dddsouthwest-web#4]
When trying to logout, the text on the page blends into the background photograph. This isn't so bad on a desktop browser but hard to read on mobile.

1. Log in to the site
2. Click the LOGOUT link
3. Browser displays https://auth.dddsouthwest.com/account/logout

![screenshot_20180130-180959](https://user-images.githubusercontent.com/89244/35767133-081aaf4e-08de-11e8-9506-69b32eb657df.png)

**Comment by josephwoodward** [comment]
This has now been fixed in the latest release.
